### ISSUE TITLE
Details required

### ISSUE THREAD

**Issue by spkprav** [ciurana2016/predict_stock_py#2]
@ciurana2016 I am new to python and also for machine learning. Please bear with me.
I have few questions, if you can answer.

1. Did you test this with real world scenario? what was the success rate?
2. Why are you predicting the next sequence value with only "Open" value, is there any possibility that I can use multiple input and then predict the next sequence?

**Comment by ciurana2016** [comment]
@spkprav Im new to machine learning too, but I'll try to answer everything.

1- The data used is real data, downloaded from google finance. I did not calculate a success rate, but if you want, you can split the data in training data and testing data, and then compare the results from your test data and the expected output, or even plot it. I based my code in [this](http://machinelearningmastery.com/time-series-prediction-with-deep-learning-in-python-with-keras/) blog post.

2- Because "Open" is the first value of every day, but it should work with "Close" too. It wont work with multiple inputs, it just takes one number at a time.

**Comment by spkprav** [comment]
@ciurana2016 Great, Thanks for your patience. This is really helpful.
